In [ ]:
%load_ext autoreload
%autoreload 2

In [1]:
from order_report import load_csv_to_dataframe, configure_log

configure_log(log_path="../logs/order_report.log")

data = load_csv_to_dataframe("../data/orders.csv")

data

,order_id,order_date,customer_id,region,product_category,quantity,unit_price,discount,returned
0,O0001,2026-01-04,C018,South,Electronics,2.0,799.0,0.0,true
1,O0002,2026-03-17,C028,North,Electronics,1.0,499.0,0.05,false
2,O0003,2026-03-13,C013,West,Electronics,2.0,2499.0,0.2,false
3,O0004,2026-01-21,C028,East,Electronics,3.0,799.0,0.05,false
4,O0005,2026-01-12,C025,North,Electronics,3.0,1299.0,0.2,false
...,...,...,...,...,...,...,...,...,...
75,O0076,2026-03-16,C002,East,Electronics,4.0,2499.0,0.05,false
76,O0077,2026-01-14,C020,North,Home,1.0,599.0,0.2,false
77,O0078,2026-01-09,C033,East,Sports,1.0,1199.0,0.15,false
78,O0079,2026-02-16,C030,South,Books,4.0,149.0,0.2,false
79,O0080,2026-03-01,C028,East,Books,3.0,149.0,0.0,false

In [2]:
from order_report import overview_order_report_dataframe

processed_data = overview_order_report_dataframe(data)

processed_data

2026-09-27 14:56:31 | INFO | order_report.validation | Dataframe validated and contain required columns: 9

,order_id,order_date,customer_id,region,product_category,quantity,unit_price,discount,returned,order_value,discounted_value
0,O0001,2026-01-04,C018,South,Electronics,2.0,799.0,0.00,True,1598.0,1598.00
1,O0002,2026-03-17,C028,North,Electronics,1.0,499.0,0.05,False,499.0,474.05
2,O0003,2026-03-13,C013,West,Electronics,2.0,2499.0,0.20,False,4998.0,3998.40
3,O0004,2026-01-21,C028,East,Electronics,3.0,799.0,0.05,False,2397.0,2277.15
4,O0005,2026-01-12,C025,North,Electronics,3.0,1299.0,0.20,False,3897.0,3117.60
...,...,...,...,...,...,...,...,...,...,...,...
75,O0076,2026-03-16,C002,East,Electronics,4.0,2499.0,0.05,False,9996.0,9496.20
76,O0077,2026-01-14,C020,North,Home,1.0,599.0,0.20,False,599.0,479.20
77,O0078,2026-01-09,C033,East,Sports,1.0,1199.0,0.15,False,1199.0,1019.15
78,O0079,2026-02-16,C030,South,Books,4.0,149.0,0.20,False,596.0,476.80
79,O0080,2026-03-01,C028,East,Books,3.0,149.0,0.00,False,447.0,447.00

In [3]:
from order_report import sales_by_category, returns_by_category, save_from_dataframe_to_csv

sales_region_df = sales_by_category(df=processed_data, category="region")
sales_product_category_df = sales_by_category(df=processed_data, category= "product_category")
return_product_category_df = returns_by_category(df=processed_data, category="product_category")


save_from_dataframe_to_csv(df=sales_region_df, file_path="../data_output/sales_by_region.csv")
save_from_dataframe_to_csv(df=sales_product_category_df, file_path="../data_output/sales_by_category.csv")
save_from_dataframe_to_csv(df=return_product_category_df, file_path="../data_output/returns_by_category.csv")

In [4]:
from order_report import overview

overview_df = overview(df= processed_data)
save_from_dataframe_to_csv(df=overview_df, file_path="../data_output/overview.csv")